### ISSUE TITLE
Do not log every request. It logs when the request comes to the existing path.

### ISSUE THREAD

**Issue by dogenius01** [AnyFetch/restify-logger#5]
Hi, I'm using restify-logger with restify to write access logs.
But, It shows the access logs when the request comes to the existing path.

**Comment by Neamar** [comment]
Hi,

I'm not sure I understand, what do you mean by "existing path"?

**Comment by dogenius01** [comment]
the path what i registered to handle the request. the routers.

In other words, the request which will be responded with 404 is not logged.

I jsut wonder is this normal behavior in restify?

**Comment by Neamar** [comment]
It is normal behavior for this logger :) If you need to log 404, you can add a listener on restify for unknown routes. How to do this depends on your restify version, I'll let you check the doc!

**Comment by dogenius01** [comment]
Thank you!.
